#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Brew
Version  : 0.02
Release  : 17
URL      : https://cpan.metacpan.org/authors/id/K/KC/KCIVEY/Text-Brew-0.02.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/K/KC/KCIVEY/Text-Brew-0.02.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Text-Brew-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Text::Brew - An implementation of the Brew edit distance in Perl, defined in
<http://ling.ohio-state.edu/~cbrew/795M/string-distance.html>

%package dev
Summary: dev components for the perl-Text-Brew package.
Group: Development
Provides: perl-Text-Brew-devel = %{version}-%{release}
Requires: perl-Text-Brew = %{version}-%{release}

%description dev
dev components for the perl-Text-Brew package.


%package perl
Summary: perl components for the perl-Text-Brew package.
Group: Default
Requires: perl-Text-Brew = %{version}-%{release}

%description perl
perl components for the perl-Text-Brew package.


%prep
%setup -q -n Text-Brew-0.02
cd %{_builddir}/Text-Brew-0.02

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Text::Brew.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Text/Brew.pm
